// CRUD routes for tasks.
// Stage 4: adds update (PUT) and delete (DELETE) endpoints.

const express = require("express");

const taskStore = require("../data/store");

const router = express.Router();

// GET /tasks
// Returns the full list of tasks. An empty list is still a valid 200 response.
router.get("/tasks", (request, response) => {
  response.json(taskStore.getAllTasks());
});

// GET /tasks/:id
// Returns a single task.
//
// Error handling:
// - The :id URL segment is always a string, so we convert it to a number.
//   If it is not numeric (e.g. /tasks/abc) there can be no matching task,
//   so we answer 404 rather than 500.
// - If the number is valid but no task has that id, we also return 404,
//   with a JSON body explaining what went wrong.
router.get("/tasks/:id", (request, response) => {
  const taskId = Number(request.params.id);

  // Non-numeric ids (NaN) cannot exist in the store -> treat as not found.
  if (Number.isNaN(taskId)) {
    return response.status(404).json({
      error: `Task with id '${request.params.id}' does not exist`,
    });
  }

  const task = taskStore.findTaskById(taskId);

  // No task with this id exists in the store -> 404 Not Found.
  if (task === null) {
    return response.status(404).json({
      error: `Task with id ${taskId} was not found`,
    });
  }

  response.json(task);
});

// POST /tasks
// Creates a new task from the JSON body: { "title": "..." }.
//
// Input validation (400 Bad Request):
// - The body must contain a "title" field.
// - The title must be a non-empty string (after trimming whitespace).
// Anything else is a client mistake, so we reject it with 400 and a JSON
// error message instead of storing bad data.
//
// On success we return 201 Created together with the stored task, including
// its server-generated id. Any "id" or "done" sent by the client is ignored:
// ids are generated by the store and new tasks always start as not done.
router.post("/tasks", (request, response) => {
  const titleFromRequest = request.body.title;

  // Missing title field entirely, wrong type, or only whitespace -> invalid.
  if (
    typeof titleFromRequest !== "string" ||
    titleFromRequest.trim().length === 0
  ) {
    return response.status(400).json({
      error: "The 'title' field is required and must be a non-empty string",
    });
  }

  const createdTask = taskStore.createTask(titleFromRequest.trim());

  response.status(201).json(createdTask);
});

// PUT /tasks/:id
// Updates an existing task. The body may contain "title" and/or "done".
//
// Error handling:
// - 400 Bad Request: the body is missing, has no usable fields, or contains
//   invalid values (title not a non-empty string, or done not a boolean).
//   We validate before touching the store so bad requests never mutate data.
// - 404 Not Found: a non-numeric id or an id that does not exist.
//
// On success we return 200 with the updated task.
router.put("/tasks/:id", (request, response) => {
  const taskId = Number(request.params.id);

  // Non-numeric ids cannot match any task -> same contract as GET /tasks/:id.
  if (Number.isNaN(taskId)) {
    return response.status(404).json({
      error: `Task with id '${request.params.id}' does not exist`,
    });
  }

  // Collect only the fields the client is allowed to update.
  const updatedFields = {};

  if (request.body.title !== undefined) {
    const titleFromRequest = request.body.title;

    // Same validation rule as POST: title must be a non-empty string.
    if (
      typeof titleFromRequest !== "string" ||
      titleFromRequest.trim().length === 0
    ) {
      return response.status(400).json({
        error: "The 'title' field must be a non-empty string",
      });
    }

    updatedFields.title = titleFromRequest.trim();
  }

  if (request.body.done !== undefined) {
    // "done" is strictly boolean; strings like "true" are rejected so the
    // stored data always keeps its expected type.
    if (typeof request.body.done !== "boolean") {
      return response.status(400).json({
        error: "The 'done' field must be a boolean",
      });
    }

    updatedFields.done = request.body.done;
  }

  // An empty body means there is nothing to update -> client error.
  if (Object.keys(updatedFields).length === 0) {
    return response.status(400).json({
      error:
        "Request body must contain at least one updatable field: 'title' or 'done'",
    });
  }

  const updatedTask = taskStore.updateTask(taskId, updatedFields);

  // Validation passed but the task does not exist -> 404 Not Found.
  if (updatedTask === null) {
    return response.status(404).json({
      error: `Task with id ${taskId} was not found`,
    });
  }

  response.json(updatedTask);
});

// DELETE /tasks/:id
// Removes a task from the store.
//
// Success returns 204 No Content: the operation succeeded and there is no
// body to send back.
// A non-numeric id or an unknown id returns 404 Not Found.
router.delete("/tasks/:id", (request, response) => {
  const taskId = Number(request.params.id);

  // Non-numeric ids cannot match any task -> treat as not found.
  if (Number.isNaN(taskId)) {
    return response.status(404).json({
      error: `Task with id '${request.params.id}' does not exist`,
    });
  }

  const wasDeleted = taskStore.deleteTask(taskId);

  // No task with this id exists -> 404 Not Found.
  if (!wasDeleted) {
    return response.status(404).json({
      error: `Task with id ${taskId} was not found`,
    });
  }

  response.status(204).send();
});

module.exports = router;
